Fix failure to find mednafen.cfg when inside bin/ or lib/ folders on Windows
AmatCoder/mednaffe pull request #130
Opened 2021-07-26 07:49 UTC by mayawarrier

It seems from reading the code that the intent is to look in the process directory for mednafen.cfg.
`g_win32_get_package_installation_directory_of_module()` returns the parent directory when the path contains "bin" or "lib".

I switched out 
`g_win32_get_package_installation_directory_of_module(NULL)`
with new function 
`win32_get_process_directory()`
instead.

2021-07-27 23:42 UTC, AmatCoder commented
Thanks for patch, it is correct but it has two issues:

1. Building Mednaffe with Cygwin is not supported.
2. `g_win32_get_package_installation_directory_of_module` function is used in [more places](https://github.com/AmatCoder/mednaffe/search?q=g_win32_get_package_installation_directory_of_module).

2021-07-29 18:41 UTC, mayawarrier commented
@AmatCoder Just made the required fixes. Let me know if more changes are needed.

2021-07-29 23:17 UTC, AmatCoder requested changes
Also `win32util.h` and `win32util.c` files should be added to `mednaffe_SOURCES` into [Makefile.am](https://github.com/AmatCoder/mednaffe/blob/master/src/Makefile.am#L43).

2021-07-29 23:17 UTC, AmatCoder commented on src/win32util.h
> +#include <gtk/gtk.h>
`#include <glib.h>` would be better.

2021-07-29 23:17 UTC, AmatCoder commented on src/win32util.c
> +#ifdef G_OS_WIN32
No need for `#ifdef G_OS_WIN32`. This is already Windows-specific code.

2021-07-29 23:17 UTC, AmatCoder commented on src/win32util.h
> +#ifdef G_OS_WIN32
No need for `#ifdef G_OS_WIN32`. This is already Windows-specific code.

2021-08-03 20:52 UTC, mayawarrier commented
hey @AmatCoder, just following up on this PR :)

2021-08-03 23:35 UTC, AmatCoder requested changes

2021-08-03 23:35 UTC, AmatCoder commented on src/Makefile.am
> +  mednaffe_SOURCES+= win32util.c win32util.h
Here you need add the files to the previous one:
`mednaffe_SOURCES+= win32util.c win32util.h widgets/joystick_windows.c`

2021-08-05 02:09 UTC, AmatCoder approved these changes

2021-08-05 02:11 UTC, merged

2021-08-05 02:13 UTC, AmatCoder commented
Merged. Thanks very much!